---
- name: Preparar e instalar Apache en EC2
  hosts: web
  become: true
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3


  tasks:
    - name: Actualizar la caché de apt
      apt:
        update_cache: yes

    - name: Asegurar que 'six' está instalado
      apt:
        name: python3-six
        state: present

    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Habilitar y arrancar Apache
      service:
        name: apache2
        enabled: true
        state: started

