name: Deploy con Ansible desde runner local

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass

      - name: Ejecutar playbook
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
