name: Deploy con Ansible desde runner local

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass

      - name: Validar que el inventario existe
        run: test -f ansible/inventory.ini

      - name: Validar sintaxis del playbook
        run: ansible-playbook --syntax-check -i ansible/inventory.ini ansible/playbook.yml

      - name: Ejecutar playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml

      - name: Verificar que Apache est\u00e1 en ejecuci\u00f3n
        run: |
          ansible web -i ansible/inventory.ini -a "systemctl is-active apache2" | grep active

